#+title: Material Icon Theme for Emacs
#+author: Daniu Zhao
#+language: en

[[https://github.com/zHaOdANiuu/material-icon.el][https://img.shields.io/badge/GitHub-zHaOdANiuu%2Fmaterial--icon.el-blue]]

Material Icon Theme integration for Emacs.  Port of the popular
[[https://github.com/material-extensions/vscode-material-icon-theme][vscode-material-icon-theme]] extension — display SVG file-type
and folder-type icons in Dired, Ibuffer, and Speedbar buffers.

*Features*

- 1,247 hand-crafted SVG icons for file types and folder names
- File-type icons in Dired (~material-icon-dired-icons-mode~)
- Mode-based icons in Ibuffer (~material-icon-ibuffer-icons-mode~)
- Folder and file icons in Speedbar (~material-icon-speedbar-icons-mode~)
- Configurable icon size

*Installation*

The package requires Emacs 27.1 or later.

*From source with ~package-vc~ (Emacs 29.1+)*

#+begin_src elisp
(use-package material-icon
  :vc (:url "https://github.com/zHaOdANiuu/material-icon.el")
  :hook ((dired-mode    . nn-dired-icons-mode)
         (ibuffer-mode  . nn-ibuffer-icons-mode)
         (speedbar-mode . nn-speedbar-icons-mode)))
#+end_src

*From source (traditional)*

#+begin_src shell
git clone https://github.com/zHaOdANiuu/material-icon.el.git
#+end_src

#+begin_src elisp
(add-to-list 'load-path "/path/to/fido-frame")
(require 'material-icon)

(add-hook dired-mode-hook #'material-icon-dired-icons-mode)
(add-hook ibuffer-mode-hook #'material-icon-ibuffer-icons-mode)
(add-hook speedbar-mode-hook #'material-icon-speedbar-icons-mode)
#+end_src

*Usage*

| Command                               | Description                             |
|---------------------------------------+-----------------------------------------|
| ~M-x material-icon-dired-icons-mode~    | Toggle file-type icons in Dired         |
| ~M-x material-icon-ibuffer-icons-mode~  | Toggle mode icons in Ibuffer            |
| ~M-x material-icon-speedbar-icons-mode~ | Toggle file/folder icons in Speedbar    |
| ~M-x material-icon-set-icon-size~       | Change icon size (default: font height) |

Install and enable globally with ~use-package~:

#+begin_src elisp
(use-package material-icon
  :ensure t
  :hook ((dired-mode    . material-icon-dired-icons-mode)
         (ibuffer-mode  . material-icon-ibuffer-icons-mode))
  :config
  (material-icon-speedbar-icons-mode 1))
#+end_src

Or manually:

#+begin_src elisp
(add-hook 'dired-mode-hook    #'material-icon-dired-icons-mode)
(add-hook 'ibuffer-mode-hook  #'material-icon-ibuffer-icons-mode)
(material-icon-speedbar-icons-mode 1)
#+end_src

*Customization*

- ~material-icon-size~ — Icon size in pixels (default: frame character height).

  #+begin_src elisp
  (setq material-icon-size 22)
  #+end_src

- ~material-icon-cache~ — Image cache; cleared automatically on size change.

*Icon Set*

This package is a port of [[https://github.com/material-extensions/vscode-material-icon-theme][vscode-material-icon-theme]].
The ~icons/~ directory contains 1,247 SVG files from the upstream
project, covering:

- 1,200+ file-type icons (by extension or filename)
- 50+ folder icons (by directory name)

*Development*

Requires [[https://github.com/doublep/eldev][Eldev]] for building and testing.

#+begin_src shell
make compile   # byte-compile all sources
make lint      # run checkdoc + package-lint + relint
make test      # run ERT tests
make run       # interactive smoke test
make clean     # remove .elc files
#+end_src

*License*

The Emacs Lisp source files in this package are licensed under
GPL-3.0-or-later.  See ~LICENSE~.

The SVG icons in the ~icons/~ directory are from
[[https://github.com/material-extensions/vscode-material-icon-theme][vscode-material-icon-theme]] and are licensed under the MIT license.
See that project's repository for details.
